sqlx-rt v0.6.3
├── sqlx-core v0.6.3
│   ├── sqlx v0.6.3
│   │   ├── indexer-sql v0.0.0 (https://github.com/left-curve/left-curve.git?branch=grug/client_traits#5b96d43a)
│   │   │   ├── grug-testing v0.0.0 (https://github.com/left-curve/left-curve.git?branch=grug/client_traits#5b96d43a)
│   │   │   │   └── grug v0.0.0 (https://github.com/left-curve/left-curve.git?branch=grug/client_traits#5b96d43a)
│   │   │   │       ├── dango-client v0.0.0 (https://github.com/left-curve/left-curve.git?branch=grug/client_traits#5b96d43a)
│   │   │   │       │   └── hyperlane-dango v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/chains/hyperlane-dango)
│   │   │   │       │       └── hyperlane-base v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/hyperlane-base)
│   │   │   │       │           ├── relayer v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/agents/relayer)
│   │   │   │       │           │   └── run-locally v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/utils/run-locally)
│   │   │   │       │           ├── run-locally v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/utils/run-locally)
│   │   │   │       │           ├── scraper v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/agents/scraper)
│   │   │   │       │           └── validator v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/agents/validator)
│   │   │   │       │           [dev-dependencies]
│   │   │   │       │           ├── hyperlane-dango v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/chains/hyperlane-dango) (*)
│   │   │   │       │           └── relayer v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/agents/relayer) (*)
│   │   │   │       ├── dango-types v0.0.0 (https://github.com/left-curve/left-curve.git?branch=grug/client_traits#5b96d43a)
│   │   │   │       │   ├── dango-client v0.0.0 (https://github.com/left-curve/left-curve.git?branch=grug/client_traits#5b96d43a) (*)
│   │   │   │       │   ├── hyperlane-base v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/hyperlane-base) (*)
│   │   │   │       │   └── hyperlane-dango v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/chains/hyperlane-dango) (*)
│   │   │   │       ├── hyperlane-base v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/hyperlane-base) (*)
│   │   │   │       ├── hyperlane-core v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/hyperlane-core)
│   │   │   │       │   ├── ecdsa-signature v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/sealevel/libraries/ecdsa-signature)
│   │   │   │       │   │   ├── hyperlane-sealevel-multisig-ism-message-id v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/sealevel/programs/ism/multisig-ism-message-id)
│   │   │   │       │   │   │   └── hyperlane-sealevel v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/chains/hyperlane-sealevel)
│   │   │   │       │   │   │       └── hyperlane-base v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/hyperlane-base) (*)
│   │   │   │       │   │   ├── hyperlane-sealevel-validator-announce v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/sealevel/programs/validator-announce)
│   │   │   │       │   │   │   └── hyperlane-sealevel v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/chains/hyperlane-sealevel) (*)
│   │   │   │       │   │   └── multisig-ism v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/sealevel/libraries/multisig-ism)
│   │   │   │       │   │       ├── hyperlane-sealevel v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/chains/hyperlane-sealevel) (*)
│   │   │   │       │   │       └── hyperlane-sealevel-multisig-ism-message-id v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/sealevel/programs/ism/multisig-ism-message-id) (*)
│   │   │   │       │   ├── ethers-prometheus v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/ethers-prometheus)
│   │   │   │       │   │   ├── hyperlane-base v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/hyperlane-base) (*)
│   │   │   │       │   │   └── hyperlane-ethereum v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/chains/hyperlane-ethereum)
│   │   │   │       │   │       ├── hyperlane-base v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/hyperlane-base) (*)
│   │   │   │       │   │       ├── relayer v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/agents/relayer) (*)
│   │   │   │       │   │       └── validator v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/agents/validator)
│   │   │   │       │   │       [dev-dependencies]
│   │   │   │       │   │       ├── scraper v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/agents/scraper)
│   │   │   │       │   │       └── validator v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/agents/validator)
│   │   │   │       │   │   [dev-dependencies]
│   │   │   │       │   │   ├── hyperlane-dango v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/chains/hyperlane-dango) (*)
│   │   │   │       │   │   ├── relayer v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/agents/relayer) (*)
│   │   │   │       │   │   └── scraper v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/agents/scraper)
│   │   │   │       │   ├── hyperlane-base v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/hyperlane-base) (*)
│   │   │   │       │   ├── hyperlane-cosmos v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/chains/hyperlane-cosmos)
│   │   │   │       │   │   ├── hyperlane-base v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/hyperlane-base) (*)
│   │   │   │       │   │   ├── run-locally v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/utils/run-locally)
│   │   │   │       │   │   └── validator v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/agents/validator)
│   │   │   │       │   ├── hyperlane-dango v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/chains/hyperlane-dango) (*)
│   │   │   │       │   ├── hyperlane-ethereum v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/chains/hyperlane-ethereum) (*)
│   │   │   │       │   ├── hyperlane-fuel v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/chains/hyperlane-fuel)
│   │   │   │       │   │   └── hyperlane-base v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/hyperlane-base) (*)
│   │   │   │       │   ├── hyperlane-sealevel v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/chains/hyperlane-sealevel) (*)
│   │   │   │       │   ├── hyperlane-sealevel-igp v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/sealevel/programs/hyperlane-sealevel-igp)
│   │   │   │       │   │   └── hyperlane-sealevel v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/chains/hyperlane-sealevel) (*)
│   │   │   │       │   ├── hyperlane-sealevel-mailbox v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/sealevel/programs/mailbox)
│   │   │   │       │   │   ├── hyperlane-sealevel v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/chains/hyperlane-sealevel) (*)
│   │   │   │       │   │   ├── hyperlane-sealevel-multisig-ism-message-id v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/sealevel/programs/ism/multisig-ism-message-id) (*)
│   │   │   │       │   │   └── hyperlane-sealevel-validator-announce v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/sealevel/programs/validator-announce) (*)
│   │   │   │       │   ├── hyperlane-sealevel-message-recipient-interface v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/sealevel/libraries/message-recipient-interface)
│   │   │   │       │   │   ├── hyperlane-sealevel v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/chains/hyperlane-sealevel) (*)
│   │   │   │       │   │   └── hyperlane-sealevel-mailbox v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/sealevel/programs/mailbox) (*)
│   │   │   │       │   ├── hyperlane-sealevel-multisig-ism-message-id v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/sealevel/programs/ism/multisig-ism-message-id) (*)
│   │   │   │       │   ├── hyperlane-sealevel-validator-announce v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/sealevel/programs/validator-announce) (*)
│   │   │   │       │   ├── hyperlane-test v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/hyperlane-test)
│   │   │   │       │   │   └── hyperlane-base v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/hyperlane-base) (*)
│   │   │   │       │   │   [dev-dependencies]
│   │   │   │       │   │   ├── relayer v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/agents/relayer) (*)
│   │   │   │       │   │   ├── scraper v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/agents/scraper)
│   │   │   │       │   │   └── validator v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/agents/validator)
│   │   │   │       │   ├── multisig-ism v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/sealevel/libraries/multisig-ism) (*)
│   │   │   │       │   ├── relayer v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/agents/relayer) (*)
│   │   │   │       │   ├── run-locally v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/utils/run-locally)
│   │   │   │       │   ├── scraper v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/agents/scraper)
│   │   │   │       │   └── validator v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/agents/validator)
│   │   │   │       │   [build-dependencies]
│   │   │   │       │   └── hyperlane-ethereum v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/chains/hyperlane-ethereum) (*)
│   │   │   │       │   [dev-dependencies]
│   │   │   │       │   └── relayer v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/agents/relayer) (*)
│   │   │   │       ├── hyperlane-dango v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/chains/hyperlane-dango) (*)
│   │   │   │       └── hyperlane-types v0.0.0 (https://github.com/left-curve/left-curve.git?branch=grug/client_traits#5b96d43a)
│   │   │   │           ├── dango-types v0.0.0 (https://github.com/left-curve/left-curve.git?branch=grug/client_traits#5b96d43a) (*)
│   │   │   │           └── hyperlane-dango v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/chains/hyperlane-dango) (*)
│   │   │   └── indexer-httpd v0.0.0 (https://github.com/left-curve/left-curve.git?branch=grug/client_traits#5b96d43a)
│   │   │       └── grug-testing v0.0.0 (https://github.com/left-curve/left-curve.git?branch=grug/client_traits#5b96d43a) (*)
│   │   ├── sea-orm v0.11.3
│   │   │   ├── migration v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/agents/scraper/migration)
│   │   │   │   └── scraper v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/agents/scraper)
│   │   │   ├── scraper v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/agents/scraper)
│   │   │   └── sea-orm-migration v0.11.3
│   │   │       └── migration v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/agents/scraper/migration) (*)
│   │   │   [dev-dependencies]
│   │   │   └── scraper v0.1.0 (/home/giacomo/github/hyperlane-monorepo/rust/main/agents/scraper)
│   │   └── sea-query-binder v0.3.1
│   │       └── sea-orm v0.11.3 (*)
│   └── sqlx-macros v0.6.3 (proc-macro)
│       └── sqlx v0.6.3 (*)
└── sqlx-macros v0.6.3 (proc-macro) (*)
